---
- name: Criacao Virtual Machine
  vmware_guest:
    datacenter: "{{ vm_datacenter }}"
    cluster: "{{ vm_cluster }}"
    name: "{{ vm_name }}"
    template: "{{ vm_template }}"
    datastore: "{{ vm_datastore }}"
#    disk:
#    - size_gb: "{{ vm_disk }}"
#      type: thin
#      datastore: "{{ vm_datastore }}"
    hardware:
      memory_gb: "{{ vm_memory }}"
      num_cpus: "{{ vm_cpu }}"
      #num_cpu_cores_per_socket: "{{ vm_cpu_cores_socket }}"
      #memory_reservation_lock: "{{ vm_memory_reservation }}"
      version: 14 # Hardware version of virtual machine
    networks:
      - name: "{{ vm_network }}"
        domain: "{{ vm_domain }}"
        start_connected: True
        connected: True
        device_type: vmxnet3
        ip: "{{ vm_ip }}"
        netmask: "{{ vm_mask }}"
        gateway: "{{ vm_gateway }}"
        type: static
        dns_servers:
          - "{{ vm_dns1 }}"
          - "{{ vm_dns2 }}"
    customization:
      hostname: "{{ vm_name }}"
      fullname: "{{ vm_name + '.' + _vm_domain }}"
      dns_servers:
        - "{{ vm_dns1 }}"
        - "{{ vm_dns2 }}"
      dns_suffix:
        - "{{ vm_domain }}"
    validate_certs: False
    folder: "{{ vm_folder }}"
    state: poweredon
    wait_for_ip_address: yes
  delegate_to: localhost
  register: deploy