---
- name: Criacao Virtual Machine
  vmware_guest:
    datacenter: "{{ VM_DATACENTER }}"
    cluster: "{{ VM_CLUSTER }}"
    name: "{{ VM_NAME }}"
    template: "{{ VM_TEMPLATE }}"
    datastore: "{{ VM_DATASTORE }}"
#    disk:
#    - size_gb: "{{ VM_DISK }}"
#      type: thin
#      datastore: "{{ VM_DATASTORE }}"
    hardware:
      memory_gb: "{{ VM_MEMORY }}"
      num_cpus: "{{ VM_CPU }}"
#      num_cpu_cores_per_socket: 2
      memory_reservation_lock: "{{ VM_MEMORY_RESERVATION }}"
      version: 14 # Hardware version of virtual machine
    networks:
      - name: "{{ VM_NETWORK }}"
        domain: "{{ VM_DOMAIN }}"
        start_connected: True
        connected: True
#        device_type: vmxnet3
        ip: "{{ VM_IP }}"
        netmask: "{{ VM_MASK }}"
        gateway: "{{ VM_GATEWAY }}"
        type: static
        dns_servers:
          - "{{ VM_DNS1 }}"
          - "{{ VM_DNS2 }}"
    customization:
      hostname: "{{ VM_NAME }}"
#      dns_servers:
#        - "{{ VM_DNS1 }}"
#        - "{{ VM_DNS2 }}"
      dns_suffix:
        - "{{ VM_DOMAIN }}"
    validate_certs: False
#    folder: /rhel/
    state: poweredon
    wait_for_ip_address: no
  delegate_to: localhost
  register: deploy